/*
 * This file is generated by jOOQ.
 */
package com.home.autowatering.entity.jooq.tables;

import com.home.autowatering.entity.jooq.DefaultSchema;
import com.home.autowatering.entity.jooq.tables.records.HibernateSequenceRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class HibernateSequence extends TableImpl<HibernateSequenceRecord> {

    /**
     * The reference instance of <code>hibernate_sequence</code>
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = new HibernateSequence();
    private static final long serialVersionUID = -639426440;
    /**
     * The column <code>hibernate_sequence.next_val</code>.
     */
    public final TableField<HibernateSequenceRecord, Long> NEXT_VAL = createField("next_val", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>hibernate_sequence</code> table reference
     */
    public HibernateSequence() {
        this(DSL.name("hibernate_sequence"), null);
    }

    /**
     * Create an aliased <code>hibernate_sequence</code> table reference
     */
    public HibernateSequence(String alias) {
        this(DSL.name(alias), HIBERNATE_SEQUENCE);
    }

    /**
     * Create an aliased <code>hibernate_sequence</code> table reference
     */
    public HibernateSequence(Name alias) {
        this(alias, HIBERNATE_SEQUENCE);
    }

    private HibernateSequence(Name alias, Table<HibernateSequenceRecord> aliased) {
        this(alias, aliased, null);
    }

    private HibernateSequence(Name alias, Table<HibernateSequenceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> HibernateSequence(Table<O> child, ForeignKey<O, HibernateSequenceRecord> key) {
        super(child, key, HIBERNATE_SEQUENCE);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HibernateSequenceRecord> getRecordType() {
        return HibernateSequenceRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HibernateSequence as(String alias) {
        return new HibernateSequence(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HibernateSequence as(Name alias) {
        return new HibernateSequence(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HibernateSequence rename(String name) {
        return new HibernateSequence(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HibernateSequence rename(Name name) {
        return new HibernateSequence(name, null);
    }
}
