/*
 * This file is generated by jOOQ.
 */
package com.home.autowatering.entiry.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Deprecated
public class Pot implements Serializable {

    private static final long serialVersionUID = 1236878930;

    private final Long id;
    private final String name;

    public Pot(Pot value) {
        this.id = value.id;
        this.name = value.name;
    }

    public Pot(
            Long id,
            String name
    ) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pot (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
