/*
 * This file is generated by jOOQ.
 */
package com.home.autowatering.entiry.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Deprecated
public class PotState implements Serializable {

    private static final long serialVersionUID = 1753570805;

    private final Long id;
    private final Date date;
    private final Double humidity;
    private final Long potId;

    public PotState(PotState value) {
        this.id = value.id;
        this.date = value.date;
        this.humidity = value.humidity;
        this.potId = value.potId;
    }

    public PotState(
            Long id,
            Date date,
            Double humidity,
            Long potId
    ) {
        this.id = id;
        this.date = date;
        this.humidity = humidity;
        this.potId = potId;
    }

    public Long getId() {
        return this.id;
    }

    public Date getDate() {
        return this.date;
    }

    public Double getHumidity() {
        return this.humidity;
    }

    public Long getPotId() {
        return this.potId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PotState (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(humidity);
        sb.append(", ").append(potId);

        sb.append(")");
        return sb.toString();
    }
}
