/*
 * This file is generated by jOOQ.
 */
package com.home.autowatering.entiry.jooq.tables;


import com.home.autowatering.entiry.jooq.DefaultSchema;
import com.home.autowatering.entiry.jooq.Indexes;
import com.home.autowatering.entiry.jooq.Keys;
import com.home.autowatering.entiry.jooq.tables.records.TankStateRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TankState extends TableImpl<TankStateRecord> {

    /**
     * The reference instance of <code>tank_state</code>
     */
    public static final TankState TANK_STATE = new TankState();
    private static final long serialVersionUID = -1487395003;
    /**
     * The column <code>tank_state.id</code>.
     */
    public final TableField<TankStateRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>tank_state.date</code>.
     */
    public final TableField<TankStateRecord, Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");
    /**
     * The column <code>tank_state.filled</code>.
     */
    public final TableField<TankStateRecord, Double> FILLED = createField("filled", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");
    /**
     * The column <code>tank_state.code</code>.
     */
    public final TableField<TankStateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");
    /**
     * The column <code>tank_state.volume</code>.
     */
    public final TableField<TankStateRecord, Double> VOLUME = createField("volume", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * Create a <code>tank_state</code> table reference
     */
    public TankState() {
        this(DSL.name("tank_state"), null);
    }

    /**
     * Create an aliased <code>tank_state</code> table reference
     */
    public TankState(String alias) {
        this(DSL.name(alias), TANK_STATE);
    }

    /**
     * Create an aliased <code>tank_state</code> table reference
     */
    public TankState(Name alias) {
        this(alias, TANK_STATE);
    }

    private TankState(Name alias, Table<TankStateRecord> aliased) {
        this(alias, aliased, null);
    }

    private TankState(Name alias, Table<TankStateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TankState(Table<O> child, ForeignKey<O, TankStateRecord> key) {
        super(child, key, TANK_STATE);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TankStateRecord> getRecordType() {
        return TankStateRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SQLITE_AUTOINDEX_TANK_STATE_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TankStateRecord> getPrimaryKey() {
        return Keys.PK_TANK_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TankStateRecord>> getKeys() {
        return Arrays.<UniqueKey<TankStateRecord>>asList(Keys.PK_TANK_STATE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TankState as(String alias) {
        return new TankState(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TankState as(Name alias) {
        return new TankState(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TankState rename(String name) {
        return new TankState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TankState rename(Name name) {
        return new TankState(name, null);
    }
}
