/*
 * This file is generated by jOOQ.
 */
package com.home.autowatering.entiry.jooq;


import com.home.autowatering.entiry.jooq.tables.Pot;
import com.home.autowatering.entiry.jooq.tables.PotState;
import com.home.autowatering.entiry.jooq.tables.TankState;
import com.home.autowatering.entiry.jooq.tables.records.PotRecord;
import com.home.autowatering.entiry.jooq.tables.records.PotStateRecord;
import com.home.autowatering.entiry.jooq.tables.records.TankStateRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code></code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PotRecord> PK_POT = UniqueKeys0.PK_POT;
    public static final UniqueKey<PotStateRecord> PK_POT_STATE = UniqueKeys0.PK_POT_STATE;
    public static final UniqueKey<TankStateRecord> PK_TANK_STATE = UniqueKeys0.PK_TANK_STATE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<PotRecord> PK_POT = Internal.createUniqueKey(Pot.POT, "pk_pot", Pot.POT.ID);
        public static final UniqueKey<PotStateRecord> PK_POT_STATE = Internal.createUniqueKey(PotState.POT_STATE, "pk_pot_state", PotState.POT_STATE.ID);
        public static final UniqueKey<TankStateRecord> PK_TANK_STATE = Internal.createUniqueKey(TankState.TANK_STATE, "pk_tank_state", TankState.TANK_STATE.ID);
    }
}
