/*
 * This file is generated by jOOQ.
 */
package com.home.autowatering.entity.jooq;


import com.home.autowatering.entity.tables.Pot;
import com.home.autowatering.entity.tables.PotState;
import com.home.autowatering.entity.tables.TankState;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_POT_1 = Indexes0.SQLITE_AUTOINDEX_POT_1;
    public static final Index SQLITE_AUTOINDEX_POT_STATE_1 = Indexes0.SQLITE_AUTOINDEX_POT_STATE_1;
    public static final Index SQLITE_AUTOINDEX_TANK_STATE_1 = Indexes0.SQLITE_AUTOINDEX_TANK_STATE_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SQLITE_AUTOINDEX_POT_1 = Internal.createIndex("sqlite_autoindex_pot_1", Pot.POT, new OrderField[]{Pot.POT.ID}, true);
        public static Index SQLITE_AUTOINDEX_POT_STATE_1 = Internal.createIndex("sqlite_autoindex_pot_state_1", PotState.POT_STATE, new OrderField[]{PotState.POT_STATE.ID}, true);
        public static Index SQLITE_AUTOINDEX_TANK_STATE_1 = Internal.createIndex("sqlite_autoindex_tank_state_1", TankState.TANK_STATE, new OrderField[]{TankState.TANK_STATE.ID}, true);
    }
}
