/*
 * This file is generated by jOOQ.
 */
package com.home.autowatering.entity.jooq;


import com.home.autowatering.entity.jooq.tables.HibernateSequence;
import com.home.autowatering.entity.jooq.tables.Pot;
import com.home.autowatering.entity.jooq.tables.PotState;
import com.home.autowatering.entity.jooq.tables.TankState;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>hibernate_sequence</code>.
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>pot</code>.
     */
    public static final Pot POT = Pot.POT;

    /**
     * The table <code>pot_state</code>.
     */
    public static final PotState POT_STATE = PotState.POT_STATE;

    /**
     * The table <code>tank_state</code>.
     */
    public static final TankState TANK_STATE = TankState.TANK_STATE;
}
