server:
  port: 8080

jdbc:
  url: jdbc:h2:mem:testdb
  driver: org.h2.Driver
  user: sa
  password:

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
