/*
 * This file is generated by jOOQ.
 */
package com.home.autowatering.entity.jooq.tables.records;


import com.home.autowatering.entity.tables.PotState;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PotStateRecord extends UpdatableRecordImpl<PotStateRecord> implements Record4<Long, Date, Double, Long> {

    private static final long serialVersionUID = 1308785156;

    /**
     * Create a detached PotStateRecord
     */
    public PotStateRecord() {
        super(PotState.POT_STATE);
    }

    /**
     * Create a detached, initialised PotStateRecord
     */
    public PotStateRecord(Long id, Date date, Double humidity, Long potId) {
        super(PotState.POT_STATE);

        set(0, id);
        set(1, date);
        set(2, humidity);
        set(3, potId);
    }

    /**
     * Getter for <code>pot_state.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pot_state.id</code>.
     */
    public PotStateRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>pot_state.date</code>.
     */
    public Date getDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>pot_state.date</code>.
     */
    public PotStateRecord setDate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>pot_state.humidity</code>.
     */
    public Double getHumidity() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>pot_state.humidity</code>.
     */
    public PotStateRecord setHumidity(Double value) {
        set(2, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pot_state.pot_id</code>.
     */
    public Long getPotId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pot_state.pot_id</code>.
     */
    public PotStateRecord setPotId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Date, Double, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Date, Double, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PotState.POT_STATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return PotState.POT_STATE.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return PotState.POT_STATE.HUMIDITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PotState.POT_STATE.POT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getHumidity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getPotId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getHumidity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getPotId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PotStateRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PotStateRecord value2(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PotStateRecord value3(Double value) {
        setHumidity(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PotStateRecord value4(Long value) {
        setPotId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PotStateRecord values(Long value1, Date value2, Double value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
