/*
 * This file is generated by jOOQ.
 */
package com.home.autowatering.entiry.jooq.tables.records;


import com.home.autowatering.entiry.jooq.tables.TankState;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TankStateRecord extends UpdatableRecordImpl<TankStateRecord> implements Record5<Long, Date, Double, String, Double> {

    private static final long serialVersionUID = 505182457;

    /**
     * Create a detached TankStateRecord
     */
    public TankStateRecord() {
        super(TankState.TANK_STATE);
    }

    /**
     * Create a detached, initialised TankStateRecord
     */
    public TankStateRecord(Long id, Date date, Double filled, String name, Double volume) {
        super(TankState.TANK_STATE);

        set(0, id);
        set(1, date);
        set(2, filled);
        set(3, name);
        set(4, volume);
    }

    /**
     * Getter for <code>tank_state.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tank_state.id</code>.
     */
    public TankStateRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tank_state.date</code>.
     */
    public Date getDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>tank_state.date</code>.
     */
    public TankStateRecord setDate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tank_state.filled</code>.
     */
    public Double getFilled() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>tank_state.filled</code>.
     */
    public TankStateRecord setFilled(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>tank_state.code</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tank_state.code</code>.
     */
    public TankStateRecord setName(String value) {
        set(3, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>tank_state.volume</code>.
     */
    public Double getVolume() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>tank_state.volume</code>.
     */
    public TankStateRecord setVolume(Double value) {
        set(4, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Date, Double, String, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Date, Double, String, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TankState.TANK_STATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return TankState.TANK_STATE.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return TankState.TANK_STATE.FILLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TankState.TANK_STATE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return TankState.TANK_STATE.VOLUME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getFilled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getVolume();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getFilled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getVolume();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TankStateRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TankStateRecord value2(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TankStateRecord value3(Double value) {
        setFilled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TankStateRecord value4(String value) {
        setName(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TankStateRecord value5(Double value) {
        setVolume(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TankStateRecord values(Long value1, Date value2, Double value3, String value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
